apiVersion: v1
kind: Secret
metadata:
  name: secret-password-postgres
type: Opaque
stringData:
  password: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
     app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres
          env:
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-password-postgres
                  key: password
          volumeMounts:
          - name: vol-secret-password-postgres
            mountPath: "/db"
            readOnly: true
      volumes:
        - name: vol-secret-password-postgres
          secret:
            secretName: secret-password-postgres
            items:
            - key: password
              path: password.txt
