apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    app: my-service
spec:
  type: NodePort 
  selector:
    app: python
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
